apiVersion: apps/v1
kind: Deployment

metadata:
  name: bella-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: bella

  template:
    metadata:
      labels:
        app: bella

    spec:
      containers:
      - name: bella-container
        image: aditya9248/bella:latest
        ports:
        - containerPort: 3000